Update create_mash_sketch.yml

diff --git a/.github/workflows/create_mash_sketch.yml b/.github/workflows/create_mash_sketch.yml
--- a/.github/workflows/create_mash_sketch.yml
+++ b/.github/workflows/create_mash_sketch.yml
@@ -54,24 +54,41 @@ jobs:
             sp=$(echo $line | awk '{print $3}')
             if [ ! -n "$sp" ] ; then sp="unknown" ; fi
             
-            echo "preparing $id $ge $sp"
+            j=0
+            while [ $j < 1 ]
+            do
+              j=2
+              date
+              echo "downloading $id $ge $sp genome"
+              datasets download genome accession $id --no-progressbar || { date ; echo "Couldn't download. Sleeping and tyring again" ; sleep 15s ; j=0 }
+            done
 
-            datasets download genome accession $id --no-progressbar
+            date
+            echo "download complete!"
+            echo "copying file"
             unzip ncbi_dataset.zip
             cp ncbi_dataset/data/*/*_genomic.fna ${ge}_${sp}_${id}.fasta
-            
+
+            date
             if [ ! -f "final.msh" ]
             then
+              echo "creating initial mash sketch"
               mash sketch ${ge}_${sp}_${id}.fasta -o final
-            else          
+            else
+              echo "creating mash sketch"
               mash sketch ${ge}_${sp}_${id}.fasta -o sample
               mv final.msh tmp.msh
+
+              date
+              echo "pasting mash sketches"
               mash paste final tmp.msh sample.msh
               rm tmp.msh sample.msh
             fi
 
             ls -alh final.msh
-  
+
+            date
+            echo "sketching complete! removing extra files"
             rm -rf ${ge}_${sp}_${id}.fasta ncbi_dataset/ ncbi_dataset.zip README.md md5sum.txt
           done < ../x${{ github.event.inputs.chunk }}.txt
 
